info:
  contact: {}
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Get list of users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get users
      tags:
      - users
swagger: "2.0"
